jenkins:
  systemMessage: "Built using configuration-as-code plugin"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD_HASH}"
